### PR TITLE
chore: add eslint with carbon config

### PR DESCRIPTION
**Pull request by lee-chase**
Part of #6 

Adds eslint and carbon config

#### Testing / Reviewing

Ran and no issues highlighted. Switched to airbnb config to see issues before switching back.

### CODE REVIEW

**Comment by davidmenendez** [comment]
I pulled this down, ran the `lint` command, and saw only `done` output, but when i look at a component like the `ExampleComponent` in VS code I see a lot of lint error highlighting showing up. so i guess my question is what is the intended result from running `yarn lint`?

**Comment by lee-chase** [comment]
> I pulled this down, ran the `lint` command, and saw only `done` output, but when i look at a component like the `ExampleComponent` in VS code I see a lot of lint error highlighting showing up. so i guess my question is what is the intended result from running `yarn lint`?

Needed quotes around 'packages/**/*.js'

**Comment by lee-chase** [comment]
Are you able to take another look at this @davidmenendez

**Review by davidmenendez — APPROVED** [review]
looks good now 👍

**Pull request merged**
