### PR TITLE
Removal modal mdx

### PR DESCRIPTION
**Pull request by davidmenendez**
Adds an MDX file for `RemovalModal` and updates some of the proptypes and documentation

#### Changelog

Use the following command to list changes or manually list out new, changed and
removed files.

M       packages/experimental-package/src/components/RemovalModal/RemovalModal.js
A       packages/experimental-package/src/components/RemovalModal/RemovalModal.mdx
M       packages/experimental-package/src/components/RemovalModal/RemovalModal.stories.js

**New**

- MDX documentation for `RemovalModal`

### CODE REVIEW

**Comment by davidmenendez** [comment]
While making these changes I was thinking about the discussion about spreading wrapped carbon component proptypes and defaultprops to the wrapper component. i think in some cases this can be easily achieved and perhaps should be done for sake of convenience, but then for a component like `RemovalModal`, which uses multiple carbon components, I think it becomes more tricky to just spread everything because there may be an overlap in prop names used between components. for instance `Modal` and `TextInput` both can take a classname, so would that class be used for both components? Do we compare every carbon component for duplicate prop names and assign them a custom prop name in the wrapper component?

Another problem becomes the spreading. If you have two carbon components you would still have to manually track all the props and assign them their own object.

```
const RemovalModal = props => {
  const modalProps = {
    className: props.modalClassName,
    body,
    ...
  };
  const inputProps = {
    className: props.inputClassName,
    placeholder,
    ...
  };
  ...
  <Modal {...modalProps}>
    <TextInput {...inputProps} />
    ...
  </Modal>
}
```

Obviously i'm up for more discussion, but I think this is a scenario that we haven't considered. In this particular case it makes sense to me to just manually pass all required props to the carbon components.

**Comment by dbrugger** [comment]
i think the key here is to avoid to overly flatten when composing

**Comment by lee-chase** [comment]
I would not suggest doing this for multiple components just the outermost wrapped component. In the case of remove, the modal dialog and the parts in normally exposes, but not the additional content such as a text box.

**Comment by davidmenendez** [comment]
i guess i just don't see a need to explicitly declare how we want to handle this sort of thing since there's no perfect catch all solution. i think we should leave it to the discretion of the author to decide which is the best method for handling how propTypes and defaultProps are shared from the parent to the children. i think in the long run we are bound to run into issues where carbon updates something and leaves us responsible for updating our code also, so I don't know if it makes sense to use that as a reason not to explicitly write out the props. as long as we are careful about locking in our carbon versions it's something that shouldn't catch us off guard and that we can prepare for.

**Comment by lee-chase** [comment]
The main reason for me is consistency. It makes maintenance easier and builds confidence with users when they dig into the source.

**Comment by davidmenendez** [comment]
i'm willing to try to find a solution that satisfies everyone, but i'm running into an issue with storybook and using spread proptypes. if i implement the following code

```
// RemovalModal.js
...
const modalProps = { ...Modal.propTypes };

RemovalModal.propTypes = {
  ...modalProps,
};

RemovalModal.defaultProps = {
  ...modalProps,
};
```

it doens't seem to work with storybook docs.

Screen Shot 2020-10-13 at 3 31 22 PM

here's that same code but with an additional manually added prop to see what happens

```
const modalProps = { ...Modal.propTypes };

RemovalModal.propTypes = {
  ...modalProps,
  test: PropTypes.bool,
};

RemovalModal.defaultProps = {
  ...modalProps,
  test: true,
};
```

Screen Shot 2020-10-13 at 3 33 54 PM

According to the storybook docs it uses [react-docgen](https://storybook.js.org/docs/react/api/argtypes#automatic-argtype-inference) to generate this table, so i'm looking around for a solution, but if it looks like i'm doing something wrong i'd love to know what i'm doing wrong.

**Comment by lee-chase** [comment]
> i'm willing to try to find a solution that satisfies everyone, but i'm running into an issue with storybook and using spread proptypes. if i implement the following code
> 
> ```
> // RemovalModal.js
> ...
> const modalProps = { ...Modal.propTypes };
> 
> RemovalModal.propTypes = {
>   ...modalProps,
> };
> 
> RemovalModal.defaultProps = {
>   ...modalProps,
> };
> ```
> 
> it doens't seem to work with storybook docs.
> 
> Screen Shot 2020-10-13 at 3 31 22 PM
> 
> here's that same code but with an additional manually added prop to see what happens
> 
> ```
> const modalProps = { ...Modal.propTypes };
> 
> RemovalModal.propTypes = {
>   ...modalProps,
>   test: PropTypes.bool,
> };
> 
> RemovalModal.defaultProps = {
>   ...modalProps,
>   test: true,
> };
> ```
> 
> Screen Shot 2020-10-13 at 3 33 54 PM
> 
> According to the storybook docs it uses [react-docgen](https://storybook.js.org/docs/react/api/argtypes#automatic-argtype-inference) to generate this table, so i'm looking around for a solution, but if it looks like i'm doing something wrong i'd love to know what i'm doing wrong.

That is correct, every property you want to support in storybook currently needs prop-types. As per discussion issue and page header.

This is a storybook issue I believe, not checked to see if one should be raised

**Comment by davidmenendez** [comment]
after searching around for a solution to this i currently am unable to find one. this may just be some weird bug or limitation of react-docgen or storybook at the moment. at the very least i think this update should be good to be merged and we can continue to discuss what we think is the best way to handle propTypes and defaultProps inheritance, although i have also been searching for this type of pattern of inheriting propsTypes and defaultProps from one component to another and i haven't been able to find anything on this topic, which i find strange. if someone can point me towards anything so i can learn more i'd really appreciate it.

**Review by lee-chase — APPROVED** [review]
LGTM guessing adding more info to docs is next up

**Pull request merged**
